### ISSUE TITLE
push_snapshot doesn't keep the promoted files csv

### ISSUE THREAD

**Issue by hieuiph** [ucesys/dremio-toolkit#7]
Hi,
thank you for your useful tool. I have a problem when I used push_snapshot to create a new data source from Dremio 1 to Dremio 2. It finished well but I figured out that all the files csv promoted on Dremio 1 now not promoted anymore on Dremio 2. Do you have any idea ? 

thanks

**Comment by mikhail-ucesys** [comment]
Hi,
Is your data source protected with credentials? If so, Dremio does not expose credentials via API. As a result, when you created a snapshot, it did not contain credentials and now push_snapshot cannot create a new data source without proper credentials. You can add password to the datasource definition in the json file that you are trying to push to Dremio 2. Please let us know if it resolved the issue.
Thanks
